### PR TITLE
Fix gh-171 & gh-172

### PR DESCRIPTION
**Pull request by bjodah**

### CODE REVIEW

**Comment by bjodah** [comment]
@matecsaj would you mind taking a look here, does this look alright to you?

**Comment by matecsaj** [comment]
Thank you for responding to all issues and so quickly.

Hs 271 is the isotope with the longest half-life, should 271 be in the lookup table instead of 270? 

Could the test be tightened as follows by omitting the equal and adding an else?

```
def test_molar_masses_of_the_elements_gh172():
     from chempy import Substance
     previous_mass = 0
     for symbol in symbols:
         this_mass = Substance.from_formula(symbol).mass
         if symbol not in ('K', 'Ni', 'I', 'Pa', 'Np', 'Am'):
             assert this_mass > previous_mass
         else:
             assert this_mass < previous_mass
         previous_mass = this_mass
```

**Comment by bjodah** [comment]
Sure, fine by me. Any serious work with Hassium isotopes would probably be better served by using actual isotope masses, also looks like the most stable isotop is 269:
https://en.wikipedia.org/wiki/Isotopes_of_hassium

But I don't know what nuclei they smash together and ratios they get...

**Comment by bjodah** [comment]
Let me know if this works for you,
and thanks again for the reports!

**Pull request merged**
